---
# .github/workflows/build-jsreport.yml
name: Build and Push jsreport Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to local registry
      run: echo "$DOCKER_PASSWORD" | docker login localhost:5000 --username "$DOCKER_USERNAME" --password-stdin

    - name: Build and push jsreport image
      run: |
        docker build -t localhost:5000/jsreport:latest .
        docker push localhost:5000/jsreport:latest

---
